### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by JTC1234567** [babroval/ford-eec-iv-diagnostic#3]
Hello, this is a great project and in hoping to make it. Any links for getting hold of a 'crumb-128'? As it's difficult to find anyone selling one.

Also i was wondering if there software is compatible with a bit of software someone else made called forddiag? This is an eec-iv diagnostic software but needs a cable with a similar looking PCB (crumb-128).

I'm also having issues with getting the Java software to work. It keeps throwing up various error messages.

Thanks

**Comment by babroval** [comment]
Hello JTC1234567

Crumb128 can be found at www.chip45.com. This is their product.
But could you first tell me your ECU number, engine type and car name,
please?
And the most important question: Are the two twisted wires coming from pins
18 and 19 of your EEC-IV?
Because many EEC-IV non-EU engines do not have DCL diagnostics.

Best wishes

**Comment by JTC1234567** [comment]
My model is Mk6 2001 finesse 1.6ltr. I'm not sure on ECU code, would have to pull out and check. It's the latter one with digital display on spedo. 
I'm pretty sure the pins 18&19 are the dcl connectors as I've looked into diagnostics before (it doesn't have the led flash codes connector on engine bay) but not had much success.

Can I not use the crumb-124 as it's only $15?

**Comment by babroval** [comment]
Yes, it looks like you have got one of the latest Escorts with DCL.
The project was written specifically for Atmega and I don't know other
devices, sorry.

**Comment by JTC1234567** [comment]
Ah no I mean if you have a look on the link you sent me and search crumb - the cheapest is listed as 'Crumb124 V4 USB RS485 Modul' however when you click on it the description says 'crumb128-4.0'. is that one for 15 euros? Just want to make sure it's the correct one?

I've had issues getting the Java project to work, another chap wrote some software called 'forddiag' which is free but you have to pay for a cable with hardware built in. Would you project be compatible with this as it's just acting as a buffer?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by babroval** [comment]
Yes, Crumb124 V4 is correct one. I have removed Crumb128. Take with
bootloader and 160,000 MHz quartz.
This project is not compatible with other devices.
If you wait a couple of weeks, I will make a video on how to program and
connect to an ECU.

Cheers

**Comment by JTC1234567** [comment]
That would be fantastic thank you! I'd really appreciate that as I'm having trouble getting the Java software to run on my pc, it keeps throwing up various errors off I try to run it.
Is that not a stand alone exe I can run rather than loading up source code?

Thanks, Joe

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by babroval** [comment]
Hello JTC1234567
Thanks for your attention to EEC-IV project..
I have uploaded connection video as you requested:
https://youtu.be/0mJQrj8HoHk/
Sorry for not very good video quality, but if you have got any questions,
please do not hesitate to ask.

Many thanks
Max

**Comment by JTC1234567** [comment]
Thank you for the tutorial, I will give it a go.
I was wondering, if I was to swap the cluster/speedo to a different one the odometer reading will be different. I have the digital dails, so the odometer reading is stored in the eeprom inside the cluster. Can the odometer reading be changed through your program via the ECU?

**Comment by babroval** [comment]
Sorry, it is only for engines
