### ISSUE TITLE
Arduino implementation

### ISSUE THREAD

**Issue by flxkrmr** [babroval/ford-eec-iv-diagnostic#5]
Sorry for opening another arduino issue, but the other one did go a bit in another direction.

I am working on an Arduino implementation to communicate with an EEC IV ECU (mainly for my 1995 Mondeo mk1).

Can you tell me a bit more what the difference is between "normal" RS485 and Fords DCL is? I read in your description that the timing is a bit different but I am not quite sure, where I have to make changes in the normal arduino serial communication.

If it is easier to explain, you can also point me to some lines in the assembler code, where the important pieces are.

Edit:
I've read in another issue that the delay between two 8 Bit Frames need to be a little shorter that in normal RS485. I put a logic analyzer on my arduino output an there is no delay between two frames, only the two stop bits. Maybe these are just a little bit shorter (e.g. 1,5 stopbits)?

**Comment by babroval** [comment]
Hello. The difference is that delay between packets in rs485 longer. The
example of the DCL delay is between lines 66 and 92 in assemler file for
sending "01 B0" code and this delay is actually shorter than in RS45
because of increasing  frequency to 38400 and than returning back to 9600.
Normally in rs45 after line 66 you would go straight to  line 92.

**Comment by flxkrmr** [comment]
I get a response from the ECU now. Thanks a lot! Much respect for your work on this! Must have taken ages to figure all this out 😄 
My analyzer can decode the response in 9600, even though it has a weird spacing between the frames. But the bytes are the same as in your PDF and it runs this synchronizing loop or whatever this is.

**Comment by babroval** [comment]
You are welcome. Old Ford communication is really challenge.

**Comment by fmcwb** [comment]
> Sorry for opening another arduino issue, but the other one did go a bit in another direction.
> 
> I am working on an Arduino implementation to communicate with an EEC IV ECU (mainly for my 1995 Mondeo mk1).
> 
> Can you tell me a bit more what the difference is between "normal" RS485 and Fords DCL is? I read in your description that the timing is a bit different but I am not quite sure, where I have to make changes in the normal arduino serial communication.
> 
> If it is easier to explain, you can also point me to some lines in the assembler code, where the important pieces are.
> 
> Edit: I've read in another issue that the delay between two 8 Bit Frames need to be a little shorter that in normal RS485. I put a logic analyzer on my arduino output an there is no delay between two frames, only the two stop bits. Maybe these are just a little bit shorter (e.g. 1,5 stopbits)?

Hi flxkrmr, i would like to work together with you to test other ecus Ford ecu's eec-iv. I have a Ford Escort 2002 mk7. 

Tks.

**Comment by flxkrmr** [comment]
Hi @fmcwb,
I created a repository on my github page and will upload the code in the next days. But it is at a really early stage and does not much so far.

**Comment by flxkrmr** [comment]
I am stuck again sorry 😄 
I receive the "sync-loop" by the ecu (00 00 00 A0, 00 00 00 B1,...). Then I wait for one circle and start answering after the first 4 byte "messages" with the blue two-byte messages from your pdf:
00 00 00 A0    **01 B0**    00 00 00 B1    **FF 5F**    00 00 00 82    **81 74**    00 00 00 93    **00 A0**
I answer in the same baud rate as the ecu (9600) and tried lots of delays between both bytes, including the delays the ecu send. The ecu does not send the 00 00 E0 message or changes the baud rate.
Am I missing something?

**Comment by babroval** [comment]
Hi. As I understand you trying to create a 'C' language code. Could you
send me your code, please?

**Comment by flxkrmr** [comment]
This is a work in progress but if you have any questions just let me know:
```
int Rs485::syncLoop(int answer) {
  int syncPointerMax = 3;
  
  unsigned char syncSig[4][4] = {
    {0x00, 0x00, 0x00, 0xa0 },
    {0x00, 0x00, 0x00, 0xb1 },
    {0x00, 0x00, 0x00, 0x82 },
    {0x00, 0x00, 0x00, 0x93 }
  };

  unsigned char answerSig[4][2] = {
    {0x01, 0xb0 },
    {0xff, 0x5f },
    {0x81, 0x74 },
    {0x00, 0xa0 }
  };
  
  if (Serial.available()) { 
    if (Serial.readBytes(read_buffer, 4) != 4) {
      return 0;
    };

    if (!memcmp(syncSig[syncPointer], read_buffer, 4)) {
      if (answer && syncPointer < 4) {
        enableWriteMode(); // setup write mode for RS485 modul
        
        Serial.end();
        softwareSerial->begin(9600);
        softwareSerial->write(answerSig[syncPointer][0]);
        delayMicroseconds(15);
        softwareSerial->write(answerSig[syncPointer][1]);

        softwareSerial->end();

        Serial.begin(9600);

        enableReadMode(); // setup write mode for RS485 modul
      }
      
      syncPointer++;

      if (syncPointer > syncPointerMax) {
        syncPointer = 0;
        return 1;
      }
    }
  }

  return 0;
}
```
I use hardware serial for reading because I think it is faster, but SoftwareSerial for writing because it has very consistent delays between the messages. By default this is one stop bit (but also some us delay after it) and I make the delay longer with the sleep method between the bytes.
This is how the messaging looks with an analyzer
![Unbenannt](https://user-images.githubusercontent.com/8393480/154033539-590fbcc9-2ee7-47b6-b11e-0920caf2d8a9.png)

**Comment by babroval** [comment]
Ok. It looks like you start sending too soon. Ford ECU doesn't turn to
receive mode.
Turning speed up and down for short time must wake it up.
Have a look at asm file from line 455 to 502.
After you get 00 00 00 A0 at 9600
make a delay of around  0.000576 seconds
then enableWriteMode()
then send $01
then delay around 0.001024 seconds
then turn speed up to 38400
then delay around 0.000012 seconds
then turn the speed back to 9600
then send $B0
then delay around 0.001024 seconds
then enableReadMode()

**Comment by flxkrmr** [comment]
Thanks, the first delay helped! It changes the baud rate now

**Comment by flxkrmr** [comment]
I think I got my first error code. Yay! Thanks again for your help :)

Do you have any idea what these codes mean? I get 0x12 0xC5 like the second one in your example

**Comment by flxkrmr** [comment]
Sorry, just found the csv file in the java code :)

**Comment by flxkrmr** [comment]
Sorry, its me again. Can you help me with reading the live data?
I was a bit confused by the pdf so I looked in the assembler code and tried to replicate what I understood. This i what I am doing now unfortunately without any response of live data:

```
read: 00 00 00 A0
write: 01 b0 01 38 11 28 08 a8 09 b8
read: 00 00 00 b1
write: ff 5f 0d f8 10 38 0f d8 15 68
read: 00 00 00 82
write: 21 f6 26 68 0c 38 04 68 0e c8
read: 00 00 00 93
write: 00 a0 16 58 1b 88 1a 98 20 08
```
The timing looks like this:

![live-data](https://user-images.githubusercontent.com/8393480/156941034-5c74b2a6-316a-4e13-a5b6-63deed28957b.png)

**Comment by mercury64** [comment]
> Do you have any idea what these codes mean? I get 0x12 0xC5 like the second one in your example

In EEC, words are stored as two bytes, where the LSB is fist then the MSB.
0x12 is the LSB, and 0xC5 is the MSB.
The word value is 0xC512.
DCL only uses 12-bits of the 16-bit word, the upper nibble is the parity check.
So, the actual data value is 512.
The parity check nibble is C.
Parity check is done by XOR three nibbles with A, example:
5 ^ 1 ^ 2 ^ A = C.
Data is valid.
